package cy.jdkdigital.productivetrees.util;

import javax.annotation.Nullable;
import java.util.HashMap;
import java.util.Map;

public record WoodSet(String woodStyle, String plankStyle, String leafStyle, String doorStyle, String saplingStyle, @Nullable String hiveStyle)
{
    public static Map<String, WoodSet> STYLES = new HashMap<>()
    {{
        put("acacia", new WoodSet("acacia", "acacia", "acacia", "oak", "acacia", "acacia"));
        put("birch", new WoodSet("birch", "birch", "birch", "oak", "birch", "birch"));
        put("cherry", new WoodSet("cherry", "cherry", "cherry", "oak", "cherry", "cherry"));
        put("dark_oak", new WoodSet("dark_oak", "dark_oak", "dark_oak", "oak", "dark_oak", "dark_oak"));
        put("jungle", new WoodSet("jungle", "jungle", "jungle", "oak", "jungle", "jungle"));
        put("mangrove", new WoodSet("mangrove", "mangrove", "mangrove", "oak", "mangrove", "mangrove"));
        put("oak", new WoodSet("oak", "oak", "oak", "oak", "oak", "oak"));
        put("spruce", new WoodSet("spruce", "spruce", "spruce", "oak", "spruce", "spruce"));
        put("bush", new WoodSet("bush", "oak", "oak", "oak", "bush", null));
        put("blackcurrant", new WoodSet("bush", "oak", "blackcurrant", "oak", "bush", null));
        put("redcurrant", new WoodSet("bush", "oak", "redcurrant", "oak", "bush", null));
        put("elderberry", new WoodSet("bush", "oak", "elderberry", "oak", "bush", null));

        put("alder", new WoodSet("alder", "alder", "alder", "oak", "oak", "fir"));
        put("allspice", new WoodSet("allspice", "allspice", "allspice", "oak", "oak", "palm"));
        put("almond", new WoodSet("almond", "almond", "almond", "oak", "acacia", "dark_oak"));
        put("apricot", new WoodSet("apricot", "apricot", "apricot", "oak", "birch", "crimson"));
        put("ash", new WoodSet("ash", "ash", "ash", "oak", "oak", "dead"));
        put("aspen", new WoodSet("aspen", "aspen", "aspen", "oak", "oak", "aspen"));
        put("avocado", new WoodSet("avocado", "avocado", "avocado", "oak", "oak", "magic"));
        put("aquilaria", new WoodSet("aquilaria", "aquilaria", "aquilaria", "oak", "dark_oak", "wisteria"));
        put("balsa", new WoodSet("balsa", "balsa", "balsa", "oak", "oak", "warped"));
        put("balsam_fir", new WoodSet("balsam_fir", "balsam_fir", "balsam_fir", "oak", "spruce", "jungle"));
        put("banana", new WoodSet("banana", "banana", "banana", "oak", "mangrove", "bamboo"));
        put("beech", new WoodSet("beech", "beech", "beech", "oak", "dark_oak", "redwood"));
        put("beliy_naliv_apple", new WoodSet("beliy_naliv_apple", "beliy_naliv_apple", "beliy_naliv_apple", "oak", "oak", "umbran"));
        put("black_cherry", new WoodSet("black_cherry", "black_cherry", "black_cherry", "oak", "birch", "wisteria"));
        put("black_locust", new WoodSet("black_locust", "black_locust", "black_locust", "oak", "oak", "oak"));
        put("blackthorn", new WoodSet("blackthorn", "blackthorn", "blackthorn", "oak", "cherry", "oak"));
        put("blue_mahoe", new WoodSet("blue_mahoe", "blue_mahoe", "blue_mahoe", "oak", "oak", "maple"));
        put("boxwood", new WoodSet("boxwood", "boxwood", "boxwood", "oak", "dark_oak", "oak"));
        put("brazil_nut", new WoodSet("brazil_nut", "brazil_nut", "brazil_nut", "oak", "acacia", "oak"));
        put("brazilwood", new WoodSet("brazilwood", "brazilwood", "brazilwood", "oak", "acacia", "cherry"));
        put("breadfruit", new WoodSet("breadfruit", "breadfruit", "breadfruit", "oak", "dark_oak", "driftwood"));
        put("buddhas_hand", new WoodSet("buddhas_hand", "buddhas_hand", "buddhas_hand", "oak", "oak", "oak"));
        put("bull_pine", new WoodSet("bull_pine", "bull_pine", "bull_pine", "oak", "spruce", "magic"));
        put("butternut", new WoodSet("butternut", "butternut", "butternut", "oak", "oak", "aspen"));
        put("cacao", new WoodSet("cacao", "cacao", "cacao", "oak", "jungle", "hellbark"));
        put("candlenut", new WoodSet("candlenut", "candlenut", "candlenut", "oak", "oak", "grimwood"));
        put("carob", new WoodSet("carob", "carob", "carob", "oak", "dark_oak", "driftwood"));
        put("cashew", new WoodSet("cashew", "cashew", "cashew", "oak", "acacia", "jacaranda"));
        put("cedar", new WoodSet("cedar", "cedar", "cedar", "oak", "spruce", "river"));
        put("ceylon_ebony", new WoodSet("ceylon_ebony", "ceylon_ebony", "ceylon_ebony", "oak", "dark_oak", "oak"));
        put("cherry_plum", new WoodSet("cherry_plum", "cherry_plum", "cherry_plum", "oak", "cherry", "umbran"));
        put("cinnamon", new WoodSet("cinnamon", "cinnamon", "cinnamon", "oak", "acacia", "mangrove"));
        put("citron", new WoodSet("citron", "citron", "citron", "oak", "oak", "willow"));
        put("clove", new WoodSet("clove", "clove", "clove", "oak", "bush", "wisteria"));
        put("cocobolo", new WoodSet("cocobolo", "cocobolo", "cocobolo", "oak", "dark_oak", "driftwood"));
        put("coconut", new WoodSet("coconut", "coconut", "coconut", "oak", "mangrove", "rosewood"));
        put("coffea", new WoodSet("coffea", "coffea", "coffea", "oak", "bush", "umbran"));
        put("copoazu", new WoodSet("copoazu", "copoazu", "copoazu", "oak", "jungle", "jungle"));
        put("copper_beech", new WoodSet("copper_beech", "copper_beech", "copper_beech", "oak", "birch", "yucca"));
        put("cork_oak", new WoodSet("cork_oak", "cork_oak", "cork_oak", "oak", "oak", "spruce"));
        put("cultivated_pear", new WoodSet("cultivated_pear", "cultivated_pear", "cultivated_pear", "oak", "oak", "maple"));
        put("date_palm", new WoodSet("date_palm", "date_palm", "date_palm", "oak", "mangrove", "palm"));
        put("dogwood", new WoodSet("dogwood", "dogwood", "dogwood", "oak", "cherry", "mangrove"));
        put("douglas_fir", new WoodSet("douglas_fir", "douglas_fir", "douglas_fir", "oak", "spruce", "jungle"));
        put("elm", new WoodSet("elm", "elm", "elm", "oak", "oak", "kousa"));
        put("european_larch", new WoodSet("european_larch", "european_larch", "european_larch", "oak", "spruce", "maple"));
        put("finger_lime", new WoodSet("finger_lime", "finger_lime", "finger_lime", "oak", "oak", "redwood"));
        put("flowering_crabapple", new WoodSet("flowering_crabapple", "flowering_crabapple", "flowering_crabapple", "oak", "cherry", "oak"));
        put("ginkgo", new WoodSet("ginkgo", "ginkgo", "ginkgo", "oak", "cherry", "grimwood"));
        put("golden_delicious_apple", new WoodSet("golden_delicious_apple", "golden_delicious_apple", "golden_delicious_apple", "oak", "oak", "oak"));
        put("grandidiers_baobab", new WoodSet("grandidiers_baobab", "grandidiers_baobab", "grandidiers_baobab", "oak", "dark_oak", "hellbark"));
        put("granny_smith_apple", new WoodSet("granny_smith_apple", "granny_smith_apple", "granny_smith_apple", "oak", "oak", "redwood"));
        put("grapefruit", new WoodSet("grapefruit", "grapefruit", "grapefruit", "oak", "oak", "driftwood"));
        put("great_sallow", new WoodSet("great_sallow", "great_sallow", "great_sallow", "oak", "mangrove", "bamboo"));
        put("greenheart", new WoodSet("greenheart", "greenheart", "greenheart", "oak", "jungle", "jungle"));
        put("juniper", new WoodSet("juniper", "juniper", "juniper", "oak", "bush", "umbran"));
        put("hawthorn", new WoodSet("hawthorn", "hawthorn", "hawthorn", "oak", "birch", "fir"));
        put("hazel", new WoodSet("hazel", "hazel", "hazel", "oak", "birch", "kousa"));
        put("kapok", new WoodSet("kapok", "kapok", "kapok", "oak", "oak", "grimwood"));
        put("key_lime", new WoodSet("key_lime", "key_lime", "key_lime", "oak", "oak", "dark_oak"));
        put("kumquat", new WoodSet("kumquat", "kumquat", "kumquat", "oak", "oak", "rosewood"));
        put("lemon", new WoodSet("lemon", "lemon", "lemon", "oak", "oak", "birch"));
        put("lime", new WoodSet("lime", "lime", "lime", "oak", "oak", "aspen"));
        put("loblolly_pine", new WoodSet("loblolly_pine", "loblolly_pine", "loblolly_pine", "oak", "spruce", "acacia"));
        put("mango", new WoodSet("mango", "mango", "mango", "oak", "oak", "cherry"));
        put("mandarin", new WoodSet("mandarin", "mandarin", "mandarin", "oak", "oak", "birch"));
        put("monkey_puzzle", new WoodSet("monkey_puzzle", "monkey_puzzle", "monkey_puzzle", "oak", "spruce", "palm"));
        put("moonlight_magic_crepe_myrtle", new WoodSet("moonlight_magic_crepe_myrtle", "moonlight_magic_crepe_myrtle", "moonlight_magic_crepe_myrtle", "oak", "dark_oak", "oak"));
        put("myrtle_ebony", new WoodSet("myrtle_ebony", "myrtle_ebony", "myrtle_ebony", "oak", "dark_oak", "oak"));
        put("nectarine", new WoodSet("nectarine", "nectarine", "nectarine", "oak", "oak", "oak"));
        put("orange", new WoodSet("orange", "orange", "orange", "oak", "oak", "yucca"));
        put("osange_orange", new WoodSet("osange_orange", "osange_orange", "osange_orange", "oak", "oak", "wisteria"));
        put("papaya", new WoodSet("papaya", "papaya", "papaya", "oak", "oak", "umbran"));
        put("peach", new WoodSet("peach", "peach", "peach", "oak", "oak", "rosewood"));
        put("pecan", new WoodSet("pecan", "pecan", "pecan", "oak", "oak", "grimwood"));
        put("pink_ivory", new WoodSet("pink_ivory", "pink_ivory", "pink_ivory", "oak", "birch", "birch"));
        put("plantain", new WoodSet("plantain", "plantain", "plantain", "oak", "mangrove", "magic"));
        put("plum", new WoodSet("plum", "plum", "plum", "oak", "cherry", "kousa"));
        put("pomelo", new WoodSet("pomelo", "pomelo", "pomelo", "oak", "oak", "aspen"));
        put("prairie_crabapple", new WoodSet("prairie_crabapple", "prairie_crabapple", "prairie_crabapple", "oak", "cherry", "umbran"));
        put("purple_blackthorn", new WoodSet("purple_blackthorn", "purple_blackthorn", "purple_blackthorn", "oak", "cherry", "jungle"));
        put("purple_crepe_myrtle", new WoodSet("purple_crepe_myrtle", "purple_crepe_myrtle", "purple_crepe_myrtle", "oak", "dark_oak", "river"));
        put("purpleheart", new WoodSet("purpleheart", "purpleheart", "purpleheart", "oak", "jungle", "birch"));
        put("rainbow_gum", new WoodSet("rainbow_gum", "rainbow_gum", "rainbow_gum", "oak", "jungle", "maple"));
        put("red_banana", new WoodSet("red_banana", "red_banana", "red_banana", "oak", "mangrove", "oak"));
        put("red_crepe_myrtle", new WoodSet("red_crepe_myrtle", "red_crepe_myrtle", "red_crepe_myrtle", "oak", "dark_oak", "oak"));
        put("red_delicious_apple", new WoodSet("red_delicious_apple", "red_delicious_apple", "red_delicious_apple", "oak", "oak", "redwood"));
        put("red_maple", new WoodSet("red_maple", "red_maple", "red_maple", "oak", "birch", "maple"));
        put("rose_gum", new WoodSet("rose_gum", "rose_gum", "rose_gum", "oak", "jungle", "mahogany"));
        put("rosewood", new WoodSet("rosewood", "rosewood", "rosewood", "oak", "birch", "rosewood"));
        put("rowan", new WoodSet("rowan", "rowan", "rowan", "oak", "birch", "dark_oak"));
        put("sand_pear", new WoodSet("sand_pear", "sand_pear", "sand_pear", "oak", "acacia", "jacaranda"));
        put("sequoia", new WoodSet("sequoia", "sequoia", "sequoia", "oak", "dark_oak", "magic"));
        put("silver_fir", new WoodSet("silver_fir", "silver_fir", "silver_fir", "oak", "spruce", "oak"));
        put("sour_cherry", new WoodSet("sour_cherry", "sour_cherry", "sour_cherry", "oak", "cherry", "umbran"));
        put("sweet_crabapple", new WoodSet("sweet_crabapple", "sweet_crabapple", "sweet_crabapple", "oak", "cherry", "oak"));
        put("silver_lime", new WoodSet("silver_lime", "silver_lime", "silver_lime", "oak", "birch", "oak"));
        put("sugar_maple", new WoodSet("sugar_maple", "sugar_maple", "sugar_maple", "oak", "birch", "maple"));
        put("swamp_gum", new WoodSet("swamp_gum", "swamp_gum", "swamp_gum", "oak", "jungle", "mahogany"));
        put("sweetgum", new WoodSet("sweetgum", "sweetgum", "sweetgum", "oak", "jungle", "oak"));
        put("tangerine", new WoodSet("tangerine", "tangerine", "tangerine", "oak", "oak", "magic"));
        put("teak", new WoodSet("teak", "teak", "teak", "oak", "birch", "dark_oak"));
        put("tuscarora_crepe_myrtle", new WoodSet("tuscarora_crepe_myrtle", "tuscarora_crepe_myrtle", "tuscarora_crepe_myrtle", "oak", "dark_oak", "oak"));
        put("walnut", new WoodSet("walnut", "walnut", "walnut", "oak", "oak", "redwood"));
        put("whitebeam", new WoodSet("whitebeam", "whitebeam", "whitebeam", "oak", "birch", "umbran"));
        put("white_poplar", new WoodSet("white_poplar", "white_poplar", "white_poplar", "oak", "birch", "river"));
        put("white_willow", new WoodSet("white_willow", "white_willow", "white_willow", "oak", "birch", "birch"));
        put("wild_cherry", new WoodSet("wild_cherry", "wild_cherry", "wild_cherry", "oak", "cherry", "rosewood"));
        put("zebrano", new WoodSet("zebrano", "zebrano", "zebrano", "oak", "jungle", "redwood"));

        put("twinkle_field", new WoodSet("twinkle_field", "twinkle_field", "twinkle_field", "oak", "jungle", "snake_block"));
    }};
}
